# Generated by Django 5.2.8 on 2025-12-09 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExamPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='试卷标题')),
                ('source_file', models.FileField(upload_to='uploads/', verbose_name='源文件')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '试卷',
                'verbose_name_plural': '试卷',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_id', models.IntegerField(help_text='原始试卷中的题号', verbose_name='题号')),
                ('q_type', models.CharField(choices=[('single_choice', '单选题'), ('multi_choice', '多选题'), ('true_false', '判断题'), ('essay', '简答题'), ('fill_blank', '填空题'), ('unknown', '未知')], default='unknown', max_length=20, verbose_name='题型')),
                ('content', models.TextField(verbose_name='题目内容')),
                ('options', models.JSONField(blank=True, help_text='例如: [{"label":"A","content":"选项内容"}]', null=True, verbose_name='选项 (JSON)')),
                ('answer', models.TextField(blank=True, verbose_name='参考答案')),
                ('explanation', models.TextField(blank=True, verbose_name='解析')),
                ('score', models.FloatField(default=0, verbose_name='分值')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.exampaper', verbose_name='所属试卷')),
            ],
            options={
                'verbose_name': '题目',
                'verbose_name_plural': '题目列表',
                'ordering': ['original_id'],
            },
        ),
    ]
