# Generated by Django 5.2.8 on 2025-12-09 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_exampaper_owner_usermistake_userprogress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermistake',
            name='created_at',
        ),
        migrations.AddField(
            model_name='usermistake',
            name='last_mistake_time',
            field=models.DateTimeField(auto_now=True, verbose_name='最近错误时间'),
        ),
        migrations.AddField(
            model_name='usermistake',
            name='mistake_count',
            field=models.IntegerField(default=1, verbose_name='错误次数'),
        ),
    ]
