# Generated by Django 5.2.8 on 2025-12-10 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_usermistake_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exampaper',
            name='is_public',
            field=models.BooleanField(default=False, help_text='勾选后所有用户可见,取消勾选则仅上传者可见', verbose_name='公开'),
        ),
    ]
